services:
  frontend:
    container_name: react
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
 
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    restart: unless-stopped
    networks:
      - docker-network
    ports: 
      - 9000:9000
    depends_on:
      - db  

  db:
    image: bitnami/postgresql:16.3.0
    platform: linux/amd64
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=laravel
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
    networks:
      - docker-network

volumes:
  db-data:

networks:
  docker-network:
    driver: bridge