services:
  frontend:
    container_name: react
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    depends_on:
      - backend
  
  backend:
    container_name: drogon
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: ./backend
      dockerfile: postgres.Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=drogon
