services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    networks:
      - app-network
  
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    build:
      context: ./backend
      dockerfile: postgres.Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=drogon
    networks:
      - app-network

networks:
  app-network:
    driver: bridge