services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - db
      - backend
    volumes:
      - ./backend:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - docker-network

  db:
    container_name: db
    image: bitnami/postgresql:16.3.0
    platform: linux/amd64
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=laravel
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
    networks:
      - docker-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "9000:9000"
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    depends_on:
      - db  
    networks:
      - docker-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - nginx
    networks:
      - docker-network
 
volumes:
  db-data:

networks:
  docker-network:
    driver: bridge